version: "3.7"
services:
  server:
    image: chouhongming/prometheus-normal-exporter
    ports:
      - "9100:9100/udp"
      - "9115:9115/udp"
      - "9116:9116/udp"
    volumes:
      - ./blackbox_exporter.yml:/etc/blackbox_exporter/blackbox_exporter.yml
      - ./snmp_exporter.yml:/etc/snmp_exporter/snmp_exporter.yml
    environment:
      - NODE_EXPORTER=true
      - BLACKBOX_EXPORTER=true
      - SNMP_EXPORTER=true
      - TIMEZONE=UTC
      - NODE_EXPORTER_OPT=
      - BLACKBOX_EXPORTER_OPT=
      - SNMP_EXPORTER_OPT=