apiVersion: v1
kind: Service
metadata:
  labels:
    app: normal-exporter
  name: normal-exporter
  namespace: [YOUR_K8S_NAMESPACE]
spec:
  ports:
  - name: blackbox
    port: 9115
    protocol: TCP
  - name: snmp
    port: 9116
    protocol: TCP
  selector:
    app: normal-exporter
  type: ClusterIP

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: [YOUR_K8S_NAMESPACE]
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
        prometheus.io/path: 'metrics'
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: chouhongming/prometheus-normal-exporter:latest
        imagePullPolicy: Always
        name: node-exporter
        env:
        - name: NODE_EXPORTER
          value: "true"
        - name: BLACKBOX_EXPORTER
          value: "false"
        - name: SNMP_EXPORTER
          value: "false"
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: node-exporter
      hostNetwork: true
      hostPID: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: normal-exporter
  name: normal-exporter
  namespace: [YOUR_K8S_NAMESPACE]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normal-exporter
  template:
    metadata:
      labels:
        app: normal-exporter
    spec:
      containers:
      - image: chouhongming/prometheus-normal-exporter:latest
        imagePullPolicy: Always
        name: normal-exporter
        env:
        - name: NODE_EXPORTER
          value: "false"
        - name: BLACKBOX_EXPORTER
          value: "true"
        - name: SNMP_EXPORTER
          value: "true"

